import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { strings } from "@/constants/strings";
import Header from "@/components/Header";
import { useEffect, useState } from "react";
import { getQuestions, getAllCategories } from "./api/triviaApi/TriviaAPI";
import { CategoryItem } from "@/components/CategoryItem";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [categories, setCategories] = useState([]);
  const [questions, setQuestions] = useState([]);

  const getCategoriesAndQuestions = async () => {
    const categoriesResponse = await getAllCategories();
    setCategories(categoriesResponse.trivia_categories);
    const questionsResponse = await getQuestions(20, "easy", "9");
    setQuestions(questionsResponse.results);
  };

  useEffect(() => {
    getCategoriesAndQuestions();
  }, []);

  return (
    <>
      <Head>
        <title>{strings.productTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div>
          <h1>Categories</h1>
          {categories.map((category) => (
            <CategoryItem item={category} />
          ))}
        </div>
      </main>
    </>
  );
}
